### PR TITLE
DEV2-2532 enterprise status bar flow

### PR DESCRIPTION
**Pull request by dimacodota**
This pr introduces five steps that are represented in the status bar:

1. The user needs to set the server URL. - The status bar will show a warning (yellow) indication and provide a "Set Settings" action.
2. The user needs to be logged in. - The status bar will show a warning indication and provide a login action.
3. Waiting for the binary to start. - The status bar will display a loading animation.
4. In case of any failure.  The status bar will show an error indication (red).
5. After a successful binary start, the status bar will display the label "Tabnine".

TBD - test, WIP in diferent pr

### CODE REVIEW

**Review by assapir — COMMENTED** [review]
I added a UserInfo request as we spoke
https://github.com/codota/acpl-paid/pull/2702

**Comment by yanir-codota** [comment]
@dimacodota can we add another error where the user is logged in but not part of the team as "you need to log in" too error?

**Comment by dimacodota** [comment]
> @dimacodota can we add another error where the user is logged in but not part of the team as "you need to log in" too error?

sure ill add it

**Comment by avnerbarr** [comment]
@dimacodota need a warning status bar if the user has tabnine installed along with the self-hosted version

**Comment by avnerbarr** [comment]
@dimacodota is this being merged?

Can you patch this :

https://github.com/codota/tabnine-vscode/blob/206ecdbee67a365ff1e81a6a7bf416568a793144/src/enterprise/extension.ts#L140

**Pull request merged**
