### PR TITLE
Loads extension after start up is finished instead of on VS Code start up

### LINKED ISSUE #533: Load extension only when necessary
https://github.com/codota/tabnine-vscode/blob/97f83b2ffc7a241653ef008394d5c50ac57d7f30/package.json#L90-L92

Why not load the extension only after start up instead of on start up of VS Code?

gz#1838

### PR DESCRIPTION
**Pull request by aravindvnair99**
Fixes #533

### CODE REVIEW

**Comment by boaz-codota** [comment]
Not sure what this PR do, could you attach link to some docs? Thanks!

**Comment by aravindvnair99** [comment]
> Not sure what this PR do, could you attach link to some docs? Thanks!

@boaz-codota Sure, please refer to [Activation Events](https://code.visualstudio.com/api/references/activation-events) in the Visual Studio Code documentation.

Quoting from the above for [*](https://code.visualstudio.com/api/references/activation-events#Start-up):

> The `*` activation event is emitted and interested extensions will be activated whenever VS Code starts up. To ensure a great user experience, please use this activation event in your extension only when no other activation events combination works in your use-case.

Quoting from the above for [onStartupFinished](https://code.visualstudio.com/api/references/activation-events#onStartupFinished):

> This activation event is emitted and interested extensions will be activated some time after VS Code starts up. This is similar to the `*` activation event, but it will not slow down VS Code startup.

**Comment by aravindvnair99** [comment]
@boaz-codota any updates?

**Comment by aravindvnair99** [comment]
@boaz-codota any updates?

**Comment by aravindvnair99** [comment]
@dimacodota could you review this PR? This is a fix for #533

**Comment by aravindvnair99** [comment]
@dimacodota any updates?

**Comment by aravindvnair99** [comment]
@dimacodota any updates on this?

**Comment by aravindvnair99** [comment]
Bump

**Comment by aravindvnair99** [comment]
@dimacodota This is pending since 2 years. Could we please have an update on this?

**Review by dimacodota — APPROVED** [review]

**Pull request merged**
